import { createSlice } from "@reduxjs/toolkit";


export const fragranceData = createSlice({
  name: "fragrance",
  initialState: {
    animal: [
        '01 Ambergris',
        '02 Castoreum', 
        '03 Musk', 
        '04 Civet cat oil', 
        '05 Hyracuem', 
        '06 Ambrette', 
        '07 Habanolide',
    ],
    woody: [
        '01 SandalWood', 
        '02 Bark', 
        '03 Cedarwood', 
        '04 Lichen', 
        '05 Guaiac wood', 
        '06 Patchouli', 
        '07 Hinoki',
        '08 Vetiver',
        '09 Oud',
    ],
    herbal: [
        '01 Flower stem', 
        '02 Ivy', 
        '03 Rosemary', 
        '04 Basil', 
        '05 Tea tree', 
        '06 Pepper mint', 
        '07 Camomile',
        '08 Lemongrass',
        '09 Verbena',
        '10 Eucalyptus',
        '11 Green tea',
        '12 Honeysuckle',
        '13 Muguet',
        '14 Green leaf',
        '15 Hyacinth',
        '16 Lemon balm',
        '17 Apple mint',
        '18 Pine',
        '19 Sage',
        '20 Darjeeling tea',
        '21 Earl grey tea',
        '22 Galbanum',
        '23 Peppermint',
        '24 Verbena',
        '25 Fig leaf',
        '26 Agave',
        '27 Bay essence',
        '28 Calamus',
        '29 Cilantro',
        '30 Vine',
        '31 Lavender',
    ],
    floral: [
        '01 Rose',
        '02 Wild flower',
        '03 Bitter orange flower',
        '04 Carnation',
        '05 Geranium',
        '06 Tulip',
        '07 Jasmin',
        '08 Jonquil',
        '09 Lilac',
        '10 Peach blossom',
        '11 Iris',
        '12 Ylang ylang',
        '13 Acacia',
        '14 Gardenia',
        '15 Violet',
        '16 Mimosa',
        '17 Magnolia',
        '18 Neroli',
        '19 Peony',
        '20 Tuberose',
        '21 White rose',
        '22 Saffron',
        '23 Cherry blossom',
        '24 Anemone',
        '25 Daisy',
        '26 Freesia',
        '27 Hydrangea',
        '28 Marigold',
        '29 Chrysanthemum',
        '30 Lily',
        '31 Pansy',
        '32 Lisianthus',
        '33 Camellia flower',
        '34 Lotus',
        '35 Myosotis',
        '36 Globe amaranth',
        '37 Black rose',
        '38 Cosmos',
        '39 Sunflower',
        '40 Statice',
    ],
    mossy: [
        '01 Oak Moss',
        '02 Tree Moss',
    ],
    citrus: [
        '01 Bergamot',
        '02 Lemon zest',
        '03 Grapefruit',
        '04 Lemon',
        '05 Lime',
        '06 Mandarine',
        '07 Orange',
        '08 Petitgrain',
        '09 Tangerin',
        '10 Yuju',
        '11 Pompia',
        '12 Calamansi',
        '13 Green tangerine',
        '14 Kumquat',
        '15 Limetta',
        '16 Pokan',
        '17 Clementine',
        '18 Blood orange',
        '19 Pomelo',
        '20 Isabella grape'
    ],
    fruity: [
        '01 Apple',
        '02 Cassis fruits',
        '03 Peach',
        '04 Blackberry',
        '05 Strawberry',
        '06 Coconut',
        '07 Cherry',
        '08 Banana',
        '09 Pineapple',
        '10 Blueberry',
        '11 Fig',
        '12 Pomegranate',
        '13 Grape',
        '14 Mango',
        '15 Pear',
        '16 Watermelon',
        '17 Raspberry',
        '18 Melon',
        '19 Green apple',
        '20 Apricot',
        '21 Kiwi',
        '22 Passion fruit',
        '23 Papaya',
        '24 Tomato',
        '25 Plum',
        '26 Japanese apricot',
        '27 Black currant',
        '28 Acai berry',
        '29 Black cherry',
        '30 Mirabelle',
        '31 Yumberry'
    ],
    powdery: [
        '01 Aldehydal',
        '02 Vanilla',
        '03 Myrr',
        '04 Benzoin',
        '05 Opoponax',
        '06 Marine',
        '07 Cascalone',
    ],
    special: [
        '01 Clove',
        '02 Cinnamon',
        '03 Leather',
        '04 Tonka nut',
        '05 Tabacco',
        '06 Black pepper',
        '07 Honey',
        '08 Fennel',
        '09 Ginger',
        '10 Pink pepper',
        '11 Turmeric',
        '12 Cinnamaldehyde',
        '13 Cacao pod',
        '14 Cassia'
    ],
  }
});